### ISSUE TITLE
Decode with headers

### ISSUE THREAD

**Issue by kvernon** [jwt-dotnet/jwt#177]
I see a way to decode to get a payload, is there a way to decode to get headers and a payload?

Thanks,
Kelly

**Comment by abatishchev** [comment]
hi, sorry for late response, it seems there is none.

**Comment by abatishchev** [comment]
can you describe your scenario? changes/pull requests are welcome!

**Comment by Andrew-Webb** [comment]
> A common scenario is reading the signing key id from the "kid" header.

As an illustration: AWS Cognito requires you to read the "kid" header when verifying that a JWT has been issued by Cognito and your User Pool within Cognito:-

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

**Comment by abatishchev** [comment]
Hey @Andrew-Webb thanks for bringing this up. Do you have any preferences or ideas this should be implemented, in pseudo code or something?

**Comment by Andrew-Webb** [comment]
Hi, @abatishchev - I have no experience of https://github.com/jwt-dotnet/jwt and was looking at it for the first time today.  My initial and immediate need is to get at the header of an AWS Cognito user pool JWT, to get its `kid` and to follow their instructions for validating such a token.  I'm part way thru implementating this by hand since https://github.com/jwt-dotnet/jwt doesn't support getting at the header and other JWT .NET implementations look over-complex to me.  I certainly like the simplicity of your package.

Later on I probably will use your package for the payload of a JWT, and will get a feel for how it works.  If at that time I have some ideas for how this package can support operations on the header, I'll post some thoughts.

At this time, I'm new to this package, and still pretty new to JWTs.  (Up until now I've only used our own OAuth2 Server and our own proprietary bearer access token format and haven't had to use JWTs.)

**Comment by abatishchev** [comment]
Thanks for the input! Working on this.

**Comment by abatishchev** [comment]
Let me close this and move the discussion to the PR.

I need someone to take a look, preferably give it a try.

**Comment by abatishchev** [comment]
please try [6.1.4](https://www.nuget.org/packages/JWT/7.0.0-beta1)
