### ISSUE TITLE
JsonNetSerializer

### ISSUE THREAD

**Issue by RoseVal** [jwt-dotnet/jwt#180]
I am using the sample code posted here to decode the token. But my application gives an error at JsonNetSerializer() saying missing assembly reference. what namespace I have to include in my .net application for this to work?

**Comment by abatishchev** [comment]
Please post exception message and stack trace

**Comment by abatishchev** [comment]
Please try version at least [4.0.0](https://www.nuget.org/packages/JWT/4.0.0), the latest stable. It depends on Newtonsoft.Json 9.0.1 so should work out of the box.

Version [2.4.2](https://www.nuget.org/packages/JWT/2.4.2) is ~2 years old and it depends on Newtonsoft.Json 6.0.4 so you would need to add assembly binding redirects in order to make it compilable.
