### ISSUE TITLE
Release Notes / Breaking Changes between versions

### ISSUE THREAD

**Issue by gjdownes** [jwt-dotnet/jwt#200]
I'm currently using v1.3.4 and I'm looking to upgrade to the latest version. Is there any place I can find release notes / change log? I just want to ensure there are no breaking changes or changes in functionality between versions.

Thanks

**Comment by abatishchev** [comment]
Hi,
Sorry but there is no change log.
There were breaking changed between each major version. The most significant is removing the static API, i.e. `JWT.JWT.*` in favor of a number of instance-based providers (namely encoder, decoder, validator).
I would strongly recommend to upgrade because there were a major security issue of exposing correct JWT in an exception message. What was addressed in version 3, iirc.
