### ISSUE TITLE
Replace Newtonsoft.Json with System.Text.Json

### ISSUE THREAD

**Issue by dazinator** [jwt-dotnet/jwt#218]
Consider switching to system.text.json for the serilialiser and removing newtonsoft dependency.

**Comment by abatishchev** [comment]
I'm not 100% sure about this idea but if this would remove a dependency then it's probably a good thing. We can release this as version `6.0.0-beta` as see the reaction.
Would you be willing to submit a PR?

**Comment by abatishchev** [comment]
Ping. You have a great idea. Would you spend some time to get it going? Would be great!

**Comment by luposky** [comment]
This would be nice, but I think it's not so easy due to some issue with System.Text.Json and Dictionary<,>:
https://github.com/dotnet/corefx/issues/40120
https://github.com/dotnet/corefx/issues/38713

In fact using this custom converter doesn't work at all (throw exception **inside** the jwt library: D:\a\1\s\src\JWT\JwtDecoder.cs:254 )

```
    public class CustomJsonSerializer : IJsonSerializer
    {
        public string Serialize(object obj)
        {
            // Implement using favorite JSON serializer
            return System.Text.Json.JsonSerializer.Serialize(obj);
        }

        public T Deserialize<T>(string json)
        {
            // Implement using favorite JSON serializer
            return System.Text.Json.JsonSerializer.Deserialize<T>(json);
        }
    }
```

**Comment by abatishchev** [comment]
Hey, that's bummer. Do you know how to adjust the interface to make it working?

Also I see that System.Text.Json supports _some_ dictionaries, e.g. where key is _string_.

**Comment by luposky** [comment]
actually serializing a Dictionary<string, object> is working fine, but **deserializing** always create a JsonElement as a value object (not a string or a int/long as supposed to be).

This workaround is working fine in my specific scenario (blazor wasm 3.1, only long and string as data objects) but, I admit, it's not very elegant:

```
   public class CustomJsonSerializer : IJsonSerializer
    {
        public string Serialize(object obj)
        {
            // Implement using favorite JSON serializer
            return System.Text.Json.JsonSerializer.Serialize(obj);
        }

        public T Deserialize<T>(string json)
        {
            // Implement using favorite JSON serializer
            var data = System.Text.Json.JsonSerializer.Deserialize<T>(json);

            if (data is Dictionary<string, object> odata)
            {
                var ndata = new Dictionary<string, object>();
                foreach (var key in odata.Keys)
                {
                    var value = (System.Text.Json.JsonElement)odata[key];
                    switch (value.ValueKind)
                    {
                        case JsonValueKind.Undefined:
                            break;
                        case JsonValueKind.Object:
                            break;
                        case JsonValueKind.Array:
                            break;
                        case JsonValueKind.String:
                            ndata.Add(key, value.GetString());
                            break;
                        case JsonValueKind.Number:
                            ndata.Add(key, value.GetInt64());
                            break;
                        case JsonValueKind.True:
                            break;
                        case JsonValueKind.False:
                            break;
                        case JsonValueKind.Null:
                            break;
                    }
                }

                if (ndata is T obj) return obj;
            }

            return data;
        }
    }
```

**Comment by luposky** [comment]
Hi @abatishchev ... sorry, but the hack above (to use the library with System.Text.Json instead of Newtonsoft.Json) don't work anymore in version 7.x

This is due to the fact that your JwtHeader class is now decorated with a **JsonProperty** (and this attribute is specific of the Newtonsoft.Json library, the equivalent System.Text.Json is called **JsonPropertyName**).

At the moment I don't think the "Custom JSON serializer" is anymore a feasible option at all if the implementation need to depend on a specific Newtonsoft.Json attribute class ...

**Comment by abatishchev** [comment]
Oh, I see. Sorry for breaking this scenario.

Do you know how to implement it differently? Let's say I remove the attributes but then `DeserializeHeader<JwtHeader>()` will stop working altogether. How to use a custom attributes or custom something else?

**Comment by luposky** [comment]
I managed to modify your library in order to work both with System.Text.Json that with Newtonsoft.Json, my assumption is that we don't need to handle others serialization library :-)

Basically this code works fine:

`
        [JsonProperty("alg")]
        [JsonPropertyName("alg")]
        public string Algorithm { get; set; }
`

along with the code posted above for handling the serialization of dictionary<string,object> in the System.Text.Json scenario ... still some limitation exist, but is more than fine for a large user case imho.

Everythings works but ... System.Text.Json is supported only in net461, netcoreapp3.0, netstandard2.0 ...

At this moment, I don't know how to conditionally apply the JsonPropertyName attribute if the destination framework is net35 or net40 ... I am going to spend some time on stackoverflow ;-)

**Comment by abatishchev** [comment]
Please share the funding! I'm more than happy to make the necessary changes to allow using other-than-Json.Net serializer. I was thinking to switch out of it altogether but so far it was parked.
