### ISSUE TITLE
Generated token is very long. 400 Bad request always happens

### ISSUE THREAD

**Issue by ibrahim-amer** [jwt-dotnet/jwt#229]
The generated token is too long in way that I can't send any parameter to endpoint beside the token. The generated token length is bigger than 260 characters wish is the max length of the URL for Web API endpoint

**Comment by abatishchev** [comment]
Hi,
It's hard to say anything concrete as you provided no details.
JWT is primarily used for authorization/authorization via HTTP header Authorization which has very high max size, see https://stackoverflow.com/questions/686217/maximum-on-http-header-values
JWT is just an encoding format and JWT.NET is just a library that encodes key-value pairs in the said format. None of that makes or accepts HTTP requests this doesn't return status codes.
The issue is in the software you're using in the way you're using it.

**Comment by ibrahim-amer** [comment]
I didn't know that the tokens can be send only using the headers as there is no docs noting that. I'm talking about sending the token string within the URL itself like so: 
http://someurl:someportnumber/api/GENERATED_TOKEN_VALUE/someendpoint

**Comment by abatishchev** [comment]
It's not they _cannot_ be sent, I'm not saying that. I'm saying that _usually_ tokens are sent via HTTP header or returned (when initially acquired after successful authentication) via HTTP response body (aka payload).

HTTP request URL has much lower max size limit than other parts of HTTP request, see https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers. So I would suggest to send the token differently.

**Comment by ibrahim-amer** [comment]
Thanks sir for your time. I'll change the way I'm sending the token

**Comment by abatishchev** [comment]
You're welcome, I'm glad I was able to help.
