### ISSUE TITLE
Decoding using fluent API throws Signature verification exception, composition API style doesn't

### ISSUE THREAD

**Issue by Sebosek** [jwt-dotnet/jwt#292]
Hi,

in version 7.2.1, the following code throws the Signature verification exception.

```csharp
new JwtBuilder()
    .WithAlgorithm(new RS256Algorithm(rsa))
    .MustVerifySignature()
    .Decode<IDictionary<string, object>>(token);
```

however, the composition API style counterpart doesn't.

```csharp
var serializer = new JsonNetSerializer();
var provider = new UtcDateTimeProvider();
var validator = new JwtValidator(serializer, provider);
var urlEncoder = new JwtBase64UrlEncoder();
var algorithm = new RS256Algorithm(rsa);
var decoder = new JwtDecoder(serializer, validator, urlEncoder, algorithm);

decoder.DecodeToObject<IDictionary<string, object>>(token);
```

From my understanding, both styles should be equal. Did I miss something?

**Comment by abatishchev** [comment]
Hi,
I think this is caused by the fact that in the former you specify to verify the signature and in the latter you call the overload which eventually passes false:
https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/IJwtDecoder.cs#L118
What's probably not right and is the legacy/backward compatible behavior worth changing.
