### ISSUE TITLE
How do I turn a JWK document into an instance of IJwtAlgorithm?

### ISSUE THREAD

**Issue by godefroi** [jwt-dotnet/jwt#301]
I am trying to validate a JWT, and I need to retrieve the key info document from the issuing authority (AD B2C in this case). That document is a JSON document containing what I believe is a JWK. How do I turn this into an instance of `IJwtAlgorithm` (RS256) to use to validate the signature on the JWT?

**Comment by abatishchev** [comment]
Hi,

To see if a string is indeed a JWT you can try to decide it using https://jwt.ms or https://jwt.io. Or using this library and pass `verify: false`.

The purpose of interface `IJwtAlgorithm` and its implementation [RS256Algorithm](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/Algorithms/RS256Algorithm.cs) that would work with AAD is to calculate and/or verify the signature of a JWT.

JWT alone is just 3 dot-separated values which then are base64-encoded: header, payload, signature. You can see the payload without a properly validated signature. You just cannot trust what you see without the validation.

In order to construct `RS256Algorithm` you basically need `X509Certificate2` with or without the private key, depending on what you're trying to achieve. Just to validate the signature it's not required, it has the constructor that accepts only the public key, exactly for this purpose.

Does it make sense to you? I'll be happy to help further if you provide more context. I'm familiar with AAD but unfortunately not much with the JWT aspect of B2C.
