### ISSUE TITLE
What is the relationship between IAlgorithmFactory and JwtAuthenticationOptions.Keys?

### ISSUE THREAD

**Issue by wtjones** [jwt-dotnet/jwt#350]
The RS256Algorithm requires a key in the ctor, yet I allow validation against multiple public keys. I handle it via something like this:

```
class RSAFactory : IAlgorithmFactory
{
…
    public IJwtAlgorithm Create(JwtDecoderContext context)
    {
    // get cert via KeyId from a kvp of identifier : publickey in settings
    var cert = GetCertFromConfig(context.Header.KeyId);
    // Also throw and log if not found

    Return new RS2560Algorithm(cert);
    }
}
```

In `Startup.cs`:

```
  services.AddAuthentication(x =>
    {
        x.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
        x.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
    }).AddJwt<RSAFactory>(options =>
    {                
         options.VerifySignature = true;
         //  keys can't be nothing but doesn’t have to be the actual keys
         options.Keys = new string[] { " "};
    }
```

Since the algorithm requires the public key, it has to be built via the factory. The options.Keys property is ignored. Is this the intended usage? The code works but I wanted to make sure that I’m not missing something.

The drawback is that I have to throw inside the factory if the KeyId doesn't match the config.

**Comment by abatishchev** [comment]
`Keys` is an unfortunate artifact of the past, when this library supported only symmetric algorithms (and I wasn't maintaining it). Since then - I have to carry it over. For asymmetric algorithms it's not needed.

But looks like it's a bug in [the code](https://github.com/jwt-dotnet/jwt/blob/5f11052347f89dbd390e59401af9cf8a8dfec44b/src/JWT/JwtDecoder.cs#L234) as it validates the keys to be not null or empty regardless.
