### ISSUE TITLE
Replace Newtonsoft with System.Text.Json

### ISSUE THREAD

**Issue by kristof12345** [jwt-dotnet/jwt#364]
Hi!

Please update to .net 6 and replace Newtonsoft with System.Text.Json.

Thanks.

**Comment by abatishchev** [comment]
Hi! It's actually 2-issues-in-1.

I might be able to come to the upgrade to .NET 6 soon as it's trivial. On other hand, since it's trivial, please don't hesitate to contribute yourself. You can use #315 as a reference 

The latter is little less trivial, see #76. Meanwhile it's already possible to substitute the serialization engine by reimplementing [IJsonSerializer](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/IJsonSerializer.cs)

**Comment by abatishchev** [comment]
By looking at the list of supported target frameworks by the [latest version](https://www.nuget.org/packages/System.Text.Json/6.0.1), I see it supports `net472` and `netstandard2.0` so we potentially can drop Json.Net, keeps it only in `net35` and `net40`.

**Comment by abatishchev** [comment]
@kristof12345 the former is done, please try version [8.8.1](https://www.nuget.org/packages/JWT/8.8.1).

For the latter, please consider contributing. I'd happy to help to get it reviewed and published in a timely manner.

**Comment by abatishchev** [comment]
@kristof12345 friendly ping on support System.Text.Json, that would be an awesome addition to the library

**Comment by hartmark** [comment]
What's missing/not working in the code added in the PR?

**Comment by abatishchev** [comment]
Yes, exactly. I outlined this idea in #76. Tried in #389 something different but it didn't work.

**Comment by hartmark** [comment]
What didn't work? I got it compiling with this small changes to your branch. 

See this PR #401

However the asserts seems to be off as it complains about not matching types.

When running the test:
Decode_To_Dictionary_Should_Return_Dictionary_When_Algorithm_Is_Symmetric

I get this error:
```
Expected token to contain value "Jesus" at key "FirstName", but found Jesus.
   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Collections.GenericDictionaryAssertions`2.Contain(TKey key, TValue value, String because, Object[] becauseArgs)
   at JWT.Tests.Builder.JwtBuilderDecodeTests.Decode_To_Dictionary_Should_Return_Dictionary_When_Algorithm_Is_Symmetric() in /home/markus/code/jwt/tests/JWT.Tests.Common/Builder/JwtBuilderDecodeTests.cs:line 313

```

Note it's complaining it cannot compare "Jesus" with Jesus, when debugging it looks like this:
![image](https://user-images.githubusercontent.com/12826053/171971788-499a93d9-6028-4880-ab8d-7e7dcdfe9244.png)


It seems to be boxed to a JsonElement and not a proper string

**Comment by hartmark** [comment]
It seems Newtonsoft.Json does some guessing about what the type of the underlying object is and System.Text.Json does the safe way to not assume anything.

So the fix is to add a custom deserializer like this:
https://josef.codes/custom-dictionary-string-object-jsonconverter-for-system-text-json/

I'm going on vacation now and will be away until Tuesday so do a gently poke to me if you don't get it up and running.
