### ISSUE TITLE
how to set Slip expiration?

### ISSUE THREAD

**Issue by 390620652** [jwt-dotnet/jwt#449]
I want to set slip expiration, but I just find the claim "exp".

**Comment by abatishchev** [comment]
hi, I think what you mean is called `sliding expiration`. Correct? Then can you elaborate what you're trying to achieve, what works and what doesn't? Then I'll be able to better assist you. However overall I'd recommend to ask on Stack Overflow (1 person vs thousands)

**Comment by 390620652** [comment]
> hi, I think what you mean is called `sliding expiration`. Correct? Then can you elaborate what you're trying to achieve, what works and what doesn't? Then I'll be able to better assist you. However overall I'd recommend to ask on Stack Overflow (1 person vs thousands)


Yes, I mean `sliding expiration`.  I want to achieve that the token will expire if the user does not access the api more than 30 minutes, but it will not expire if the user access api continually。

**Comment by abatishchev** [comment]
Hi, sorry for a late response!
JWT is immutable so in order to extend its validity you would need to issue the customer a new token. Possible if the server is the token's issuer, and less so if not, e.g. the token is issued by a cloud provider such as Azure AD.
However what you're looking for then sounds like a refresh token, a special token that allows the caller to acquire a new access token.
I'd suggest using the standard mechanisms, protocols and flows, and not trying to come with a homegrown solution. The biggest risks of such is that it might end up being insecure.
