### ISSUE TITLE
Is same Secret Key matter?

### ISSUE THREAD

**Issue by ammar91** [jwt-dotnet/jwt#59]
I'm sorry but this is more of question rather than an issue, since I can not find any appropriate place where to ask question.

Assuming that I have a secret key "top secret" and I used this to encode same data multiple times, will jwt always generate unique token?

Will jwt always generate unique token no matter if same secret key use to encode different data?

**Comment by abatishchev** [comment]
Hi,
I'm not really a Jwt pro but I think it will generate unique token for differ data and the same token for the same days if you run it multiple times.
See method [Encode]( https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JWT.cs#L77), it doesn't uses only input and doesn't use anything external such current timestamp to generate the token.

**Comment by dlongest** [comment]
For the same input and secret key, a hash function will produce the same output - determinism is a basic property of hash functions.  See https://en.wikipedia.org/wiki/Hash_function.  Separate the concept of hash within the JWT library and just consider it in its other uses.  For example, the GetHashCode method on object returns a hash representing the state of the object.  It should always return the same value given the same object state else some of its semantics (locating it in a collection for example) wouldn't be possible.  Thus within JWT, the same token should be generated for the same header and data payloads.  However, any difference in either, no matter how small, will cause a different hash to be generated. 

It's also worth mentioning that hashing applied to passwords typically functions in a slightly different way.  Because hashes are simply functions of their input, it is important in password stores that 2 users not have the same hashed value even if their password is the same.  To achieve that, passwords are salted with some arbitrary or random value to force them to be different from each other as input to a hash function to offer better password protection.  Again, difference in output is due to the use of a random salt applied to the data (thus altering the input) and that is not present within the JWT library.
