### ISSUE TITLE
How to use this library with Asp.net Web Api Core?

### ISSUE THREAD

**Issue by coderabsolute** [jwt-dotnet/jwt#78]
I have been successfully using this library with the previous Web Api with absolutely no problems. Now, I'm starting a brand new project with `Asp.net Core Web Api`, however I can still generate tokens but I don't know how to hook this up with the Controller's Authorize Attribute. Can someone please provide me a sample or something?

**Comment by abatishchev** [comment]
I don't think such questions are related to Jwt.Net. Rather to ASP.NET Core itself. So Stack Overflow would be a better place to ask (and get the right answer faster).

I see there is a way to inject into `[ActionFilter]` attribute, might be a way to do the same into `[AuthorizeAttribute]` too. See http://stackoverflow.com/questions/36109052/inject-service-into-action-filter

**Comment by nbarbettini** [comment]
Hey @coderabsolute - just a few quick tips since I've had to do this before:

* If you've already got the token generation part down, then technically all you need is the `UseJwtBearerAuthentication` middleware: https://andrewlock.net/a-look-behind-the-jwt-bearer-authentication-middleware-in-asp-net-core/
* Something like [OpenIddict](https://github.com/openiddict/openiddict-core) might be useful if you want to do ASP.NET Core Identity + tokens + OpenID Connect.

I wrote an overview of a lot of this stuff, which might be useful for you: https://stormpath.com/blog/token-authentication-asp-net-core

**Comment by coderabsolute** [comment]
Hey @nbarbettini - many thanks for your post, much appreciated!
